### ISSUE TITLE
Finer control/configure formatted and linter

### ISSUE THREAD

**Issue by michaelsimonelli** [jshinonome/vscode-k-pro#1]
Sometimes when formatter is applied, it ruins function definition/spacing/and indent.

mostly with lists and vector conditionals sometimes expanding to single line vs multiline

(data1; data2)

vs

(
    data1;
    data2
)

should be configurable

same with 

$[1b;100;200]

vs

$[
    1b;
        100;
        200] 

Should also be able to configure closing bracket indent

if[…
] (in line with “i” of if/start of statement
vs
if[…
   ] (in line with opening bracket “[“

same with $[]
- inline with start or statement (beginning of variable name or $)
- inline with opening bracket

And noticed a few issues with brackets in linter

$[flag: [a: 100;a];[b: 200;b]] - throws a warning “Unexpected use of [“

but this is technical valid and sometimes needed for more complex conditionals (image attached)

![image](https://github.com/jshinonome/vscode-k-pro/assets/39355436/00f99c81-004d-4a83-b9e9-052acb9edb1d)

would be nice to configure linter options as well as provide decorator to suppress warnings/errors or functions/lines
E.g.:
@kpro-lint-ignore
@kpro-lint-supress-block

would be happy to help if looking for contributors

thanks

**Comment by jshinonome** [comment]
There is a comment to skip formatter for the block, I will update the plugin guidance.

// k-pro-ignore

I may add formatter/linter configuration in the future, but my goal is making something like black/ruff for python.

q is too flexible in some sense, so I intend to force some formats, e.g. the semicolon after if[] and not allow [] in $[]. 

If you are strongly believe that there are some code that I should fix, please provide detailed code snippets.

Not looking for contributors at the moment.

If there are more subscriptions to k-pro, I could hire someone to work on details and more features.

**Comment by jshinonome** [comment]
Sorry, I didn't notice that you updated the issue. I only get notified when there is a reply.

I upgrade k-pro to 3.3.3 to include the following two ignore comments.

- `// k-pro-ignore-linter`: ignore linter for the following block of code
- `// k-pro-ignore-formatter`: ignore formatter for the following block of code (only works at top blocks)
